export const CHANGE_USER_MESSAGE_TEXT = 'CHANGE-USER-MESSAGE-TEXT';
export const ADD_MESSAGE = 'ADD-MESSAGE';
export const CHANGE_POST_TEXT = 'CHANGE-POST-TEXT';
export const ADD_POST = 'ADD-POST';
export const FOLLOW = 'FOLLOW';
export const UNFOLLOW = 'UNFOLLOW';
export const USERS_QUERY ='USERS-QUERY';
export const CURRENT_PAGE = 'CURRENT-PAGE';
export const TOTAL_COUNT = 'TOTAL-COUNT';